### ISSUE TITLE
Melpe stable

### ISSUE THREAD

**Issue by nlamirault** [vapniks/syslog-mode#12]
could you please create a tag to use this package using melpa stable [1].
Thanks

[1] : http://stable.melpa.org/

**Comment by tarsius** [comment]
I second that request.

When you do it, then don't forget to also update the `Version` header keyword in the library itself.

(Actually I would recommend to instead *remove* that header keyword along with `Last-Updated`. The values of both keywords are currently (and most of the time) incorrect, and in the age of Git they don't really serve any purpose anymore.

**Comment by vapniks** [comment]
OK, done.

**Comment by tarsius** [comment]
Thanks!
